from electrons.common.continous_e_beam import get_continous_beam_pde_solver
from electrons.common.generic_electron_solver import GenericElectronSolver

ContinousBeamPDEsolver = get_continous_beam_pde_solver(GenericElectronSolver)
