from electrons.common.generic_electron_solver import GenericElectronSolver
from electrons.common.pulsed_e_beam import get_pulsed_beam_pde_solver

PulsedBeamPDEsolver = get_pulsed_beam_pde_solver(GenericElectronSolver)
