from hadrons.common.generic_hadron_solver import GenericHadronSolver
from hadrons.common.initial_recombination import get_initial_recombination_pde_solver

InitialHadronSolver = get_initial_recombination_pde_solver(GenericHadronSolver)
