name: Python tests

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  example_test:
    if: >
      !contains(needs.initialise.outputs.commit_message, '[ci skip]') &&
      !contains(needs.initialise.outputs.commit_message, '[skip ci]')
    name: Fast tests
    runs-on:  ${{ matrix.platform }}
    strategy:
       matrix:
         python-version: ['3.8', '3.9', '3.10']
         platform: [ubuntu-latest]  # TODO add Windows as well
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python --version
          pip --version
          pip install -r requirements.txt

      - name: Compile Cython modules
        run: make -j2
        working-directory: hadrons/cython_files
          
      - name: Run example script
        run: PYTHONPATH=. python example_single_track.py
        # working-directory: hadrons

      - name: Install test dependencies
        run: pip install pytest

      - name: Run unit and integration tests
        run: PYTHONPATH=. python -m pytest
