name: Python tests

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  example_test:
    if: >
      !contains(needs.initialise.outputs.commit_message, '[ci skip]') &&
      !contains(needs.initialise.outputs.commit_message, '[skip ci]')
    name: Fast tests
    runs-on:  ${{ matrix.platform }}
    strategy:
       matrix:
         python-version: ['3.8', '3.9', '3.10']
         platform: [ubuntu-latest]  # TODO add Windows as well
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and iontracks package
        run: |
          python --version
          pip --version
          CYTHONIZE=1 pip install --editable .

      - name: Run example script
        run: python example_single_track.py
        working-directory: hadrons

      - name: Install test dependencies
        run: pip install pytest pytest-xdist

      - name: Run unit and integration tests
        run: python -m pytest -n 2
